- pkg:maven/sh.platform/config@2.2.0
- pkg:maven/sh.platform/config@2.2.0?classifier=sources
- pkg:maven/sh.platform/config@2.2.1
- pkg:maven/sh.platform/config@2.2.1?classifier=sources
- pkg:maven/sh.platform/config@2.2.2
- pkg:maven/sh.platform/config@2.2.2?classifier=sources
- pkg:maven/sh.platform/config@2.2.3
- pkg:maven/sh.platform/config@2.2.3?classifier=sources
