- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-core@0.15.0
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-core@0.15.0?classifier=sources
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-core@0.17.9
- pkg:maven/io.muenchendigital.digiwf/digiwf-camunda-prometheus-core@0.17.9?classifier=sources
