- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.14.10?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.14.11?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.14.12?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.14.13?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.14.2?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.14.3?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.14.4?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.14.5?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.14.6?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.14.7?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.14.8?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.14.9?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.15.0?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.15.1?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.15.2?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.16.0?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.16.10?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.16.11?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.16.12?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.16.13?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.16.1?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.16.2?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.16.3?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.16.4?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.16.5?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.16.6?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.16.7?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.16.8?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.16.9?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.17.0?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.17.10?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.17.11?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.17.1?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.17.2?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.17.3?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.17.4?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.17.5?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.17.6?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.17.7?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.17.8?classifier=sources
- pkg:maven/com.avast.gradle/gradle-docker-compose-plugin@0.17.9?classifier=sources
