- pkg:maven/io.johnsonlee.gradle/gradle-prometheus-plugin@1.0.0?classifier=sources
- pkg:maven/io.johnsonlee.gradle/gradle-prometheus-plugin@1.1.0?classifier=sources
- pkg:maven/io.johnsonlee.gradle/gradle-prometheus-plugin@1.2.0?classifier=sources
- pkg:maven/io.johnsonlee.gradle/gradle-prometheus-plugin@1.3.0?classifier=sources
- pkg:maven/io.johnsonlee.gradle/gradle-prometheus-plugin@1.4.0?classifier=sources
- pkg:maven/io.johnsonlee.gradle/gradle-prometheus-plugin@1.5.0?classifier=sources
- pkg:maven/io.johnsonlee.gradle/gradle-prometheus-plugin@2.0.0?classifier=sources
- pkg:maven/io.johnsonlee.gradle/gradle-prometheus-plugin@2.1.0?classifier=sources
