- pkg:maven/org.apache.druid.extensions.contrib/prometheus-emitter@0.22.0
- pkg:maven/org.apache.druid.extensions.contrib/prometheus-emitter@0.22.0?classifier=sources
- pkg:maven/org.apache.druid.extensions.contrib/prometheus-emitter@0.22.1
- pkg:maven/org.apache.druid.extensions.contrib/prometheus-emitter@0.22.1?classifier=sources
- pkg:maven/org.apache.druid.extensions.contrib/prometheus-emitter@0.23.0
- pkg:maven/org.apache.druid.extensions.contrib/prometheus-emitter@0.23.0?classifier=sources
- pkg:maven/org.apache.druid.extensions.contrib/prometheus-emitter@24.0.0
- pkg:maven/org.apache.druid.extensions.contrib/prometheus-emitter@24.0.0?classifier=sources
- pkg:maven/org.apache.druid.extensions.contrib/prometheus-emitter@24.0.1
- pkg:maven/org.apache.druid.extensions.contrib/prometheus-emitter@24.0.1?classifier=sources
