- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@1999.10?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2021.11?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2021.9?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2022.06?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2022.09?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2022.10?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2022.11?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2022.12?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2023.02?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2023.03?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2023.04?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2023.05?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2023.07?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2023.08?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2023.09?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2023.10?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2023.11?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2023.12?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2023.2.01?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2023.3.01?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2024.01?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2024.02?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2024.03?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2024.04?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2024.05?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2024.06?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2024.07?classifier=sources
