- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2021.11?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2021.9?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2022.06?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2022.09?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2022.10?classifier=sources
- pkg:maven/io.github.shuigedeng/taotao-cloud-starter-prometheus@2022.11?classifier=sources
