- pkg:maven/io.prometheus/prometheus-metrics-exporter-opentelemetry-no-otel@1.3.10?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-opentelemetry-no-otel@1.3.7?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-opentelemetry-no-otel@1.3.8?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-opentelemetry-no-otel@1.3.9?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-opentelemetry-no-otel@1.4.0?classifier=sources
- pkg:maven/io.prometheus/prometheus-metrics-exporter-opentelemetry-no-otel@1.4.1?classifier=sources
