- pkg:maven/org.kairosdb.metrics4jplugin/prometheus@0.5.0
- pkg:maven/org.kairosdb.metrics4jplugin/prometheus@0.5.0?classifier=sources
- pkg:maven/org.kairosdb.metrics4jplugin/prometheus@0.6.0
- pkg:maven/org.kairosdb.metrics4jplugin/prometheus@0.6.0?classifier=sources
